# Generated by Django 4.1.5 on 2023-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostEventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('is_interested', models.BooleanField(default=False)),
                ('expected_join_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
