# Generated by Django 4.1.5 on 2023-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteventfeedback',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='permanent_address',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='phone',
            field=models.CharField(max_length=99),
        ),
    ]
