# Generated by Django 4.1.5 on 2023-02-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_productquantity_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='quantity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.productquantity'),
            preserve_default=False,
        ),
    ]
