# Generated by Django 4.1.5 on 2023-02-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_order_quantity_shop_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='quantity',
        ),
    ]
