# Generated by Django 4.1.5 on 2023-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_shop_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.AddField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
