# Generated by Django 4.1.5 on 2023-02-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_productquantity_shop_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
