# Generated by Django 4.1.5 on 2023-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_productquantity_alter_order_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
