# Generated by Django 4.1.5 on 2023-02-21 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_blog_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
    ]
