# Generated by Django 4.1.5 on 2023-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_blog_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_excerpt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
