# Generated by Django 4.1.5 on 2023-03-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_blog_blog_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='founder_image',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to=''),
        ),
    ]
