# Generated by Django 4.1.5 on 2023-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_basicinfo_founder_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='founder_image',
            field=models.ImageField(blank=True, max_length=400, upload_to='upload/basic_info'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(blank=True, max_length=999, null=True, upload_to='upload/blog'),
        ),
    ]
