# Generated by Django 4.1.5 on 2023-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_basicinfo_founder_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='founder_image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='upload/basic_info'),
        ),
    ]
