# Generated by Django 4.1.5 on 2023-03-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_basicinfo_link_and_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='about_mission',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='about_vision',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='link_and_resources',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='privacy_policy',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='terms_of_service',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
