# Generated by Django 4.1.5 on 2023-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_basicinfo_about_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='helpful_forms',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
