# Generated by Django 4.1.5 on 2023-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_basicinfo_helpful_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='consultation_request',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
