# Generated by Django 4.1.5 on 2023-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_basicinfo_consultation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='services_page',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
