# Generated by Django 4.1.5 on 2023-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.JSONField(blank=True),
        ),
    ]
