# Generated by Django 4.1.5 on 2023-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_order_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
