# Generated by Django 4.1.5 on 2023-04-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_basicinfo_about_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='company',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
