# Generated by Django 4.1.5 on 2023-04-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_consultationrequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
