# Generated by Django 4.1.5 on 2023-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_consultationrequest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Unapproved', 'Unapproved'), ('Completed', 'Completed'), ('Shipped', 'Shipped')], default='unapproved', max_length=100),
        ),
    ]
