# Generated by Django 4.1.5 on 2023-03-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='picture',
            field=models.ImageField(blank=True, default='customuser/bell.png', max_length=400, upload_to='customuser/'),
        ),
    ]
