# Generated by Django 4.1.5 on 2023-04-21 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_app', '0008_alter_event_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMCQQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=999)),
                ('option1', models.CharField(max_length=999)),
                ('option2', models.CharField(max_length=999)),
                ('option3', models.CharField(max_length=999)),
                ('option4', models.CharField(max_length=999)),
                ('correct_answer', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('total_answers', models.IntegerField()),
                ('total_participates', models.IntegerField()),
                ('total_feedbacks', models.IntegerField()),
                ('event_durations', models.TimeField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_summary', to='event_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventWrittenQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=999)),
                ('answers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_event', to='event_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ask_question', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event_question', to='event_app.event')),
                ('mcq_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mcq_question', to='event_app.eventmcqquestions')),
                ('written_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='written_question', to='event_app.eventwrittenquestions')),
            ],
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EventQuestions',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to='event_app.eventregistration'),
        ),
    ]
