# Generated by Django 4.1.5 on 2023-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_eventmcqquestions_eventsummary_eventwrittenquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='attendance_qr',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
    ]
