# Generated by Django 4.1.5 on 2023-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_alter_event_attendance_qr_alter_event_event_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, upload_to='event/'),
        ),
    ]
