# Generated by Django 4.1.5 on 2023-04-21 08:02

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_alter_event_event_link_alter_event_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='dob',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
