# Generated by Django 4.1.5 on 2023-04-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0017_rename_loation_eventregistration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_info',
            field=models.JSONField(blank=True),
        ),
    ]
