# Generated by Django 4.1.5 on 2023-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0018_alter_eventregistration_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_link',
        ),
        migrations.AddField(
            model_name='event',
            name='event_location_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
