# Generated by Django 4.1.5 on 2023-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0019_remove_event_event_link_event_event_location_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendance_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_topic',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_numbers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
