# Generated by Django 4.1.5 on 2023-04-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0020_alter_event_attendance_link_alter_event_event_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant_numbers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
