# Generated by Django 4.1.5 on 2023-04-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0021_alter_event_participant_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_views', to='event_app.event')),
            ],
        ),
    ]
