# Generated by Django 4.1.5 on 2023-04-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0023_eventregistration_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenPollsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=999, null=True)),
                ('option1', models.CharField(blank=True, max_length=999, null=True)),
                ('option2', models.CharField(blank=True, max_length=999, null=True)),
                ('option3', models.CharField(blank=True, max_length=999, null=True)),
                ('option4', models.CharField(blank=True, max_length=999, null=True)),
                ('results', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventmcqquestions',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='eventmcqquestions',
            name='option1',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='eventmcqquestions',
            name='option2',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='eventmcqquestions',
            name='option3',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='eventmcqquestions',
            name='option4',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='eventmcqquestions',
            name='question',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='poll_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='polls_question', to='event_app.evenpollsquestions'),
        ),
    ]
