# Generated by Django 4.1.5 on 2023-04-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0025_eventmcqquestions_created_at_eventmcqquestions_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmcqquestions',
            name='asked',
            field=models.BooleanField(default=False),
        ),
    ]
