# Generated by Django 4.1.5 on 2023-04-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0031_evenpollsquestions_asked_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenPollsQuestions',
            new_name='EventPollsQuestions',
        ),
        migrations.CreateModel(
            name='EventWrittenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.eventwrittenquestions')),
            ],
        ),
        migrations.CreateModel(
            name='EventPollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=999)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.eventpollsquestions')),
            ],
        ),
        migrations.CreateModel(
            name='EventMcqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=999)),
                ('correct_answer', models.CharField(max_length=999)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.eventmcqquestions')),
            ],
        ),
    ]
