# Generated by Django 4.1.5 on 2023-04-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0032_rename_evenpollsquestions_eventpollsquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmcqquestions',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpollsquestions',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventwrittenquestions',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
