# Generated by Django 4.1.5 on 2023-05-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event_app", "0036_event_club_alter_eventregistration_payment_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="payment_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event_app.paymentinfo",
            ),
        ),
    ]
