# Generated by Django 4.1.2 on 2022-12-31 13:56

import assesment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assesment', '0002_assesment_posted_date_assesment_posted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='assesment',
            name='scores',
        ),
        migrations.CreateModel(
            name='AssessmentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=assesment.models.default_score_json)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_by_user', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_object', to='assesment.assesment')),
            ],
        ),
    ]
