# Generated by Django 4.1.2 on 2022-12-31 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assesment', '0003_remove_assesment_assessed_by_remove_assesment_scores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentCount',
            new_name='AssessmentScores',
        ),
    ]
