# Generated by Django 4.1.5 on 2023-02-24 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points_and_badges', '0002_rename_badge_weeklybookreadingpointtable_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadingpointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_reader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meditationpointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meditation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalpointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationshippointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklybookreadingpointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_book_reader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklymeditationpointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_meditation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyphysicalpointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_workout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyrelationshippointtable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
