# Generated by Django 4.1.5 on 2023-02-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postImage',
        ),
    ]
