# Generated by Django 4.1.5 on 2023-02-26 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_remove_post_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_uploaded', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiprecord_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
