# Generated by Django 4.1.5 on 2023-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_tiprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiprecord',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
