# Generated by Django 4.1.5 on 2023-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_tiprecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
