# Generated by Django 4.1.5 on 2023-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_tiprecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postMedia',
        ),
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
