# Generated by Django 4.1.5 on 2023-03-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_post_postmedia_post_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postImage',
            new_name='postMedia',
        ),
    ]
