# Generated by Django 4.1.5 on 2023-03-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_post_postdescription'),
        ('feed', '0007_remove_post_postmedia_post_postimage'),
    ]

    operations = [
    ]
