# Generated by Django 4.1.5 on 2023-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_merge_20230315_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='story/'),
        ),
    ]
