# Generated by Django 4.1.5 on 2023-03-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_rename_postimage_post_postmedia'),
        ('feed', '0009_alter_post_postdescription_alter_story_media'),
    ]

    operations = [
    ]
