# Generated by Django 4.1.5 on 2023-03-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_story_media'),
        ('feed', '0010_merge_20230315_0606'),
    ]

    operations = [
    ]
