# Generated by Django 4.1.5 on 2023-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
