# Generated by Django 4.1.5 on 2023-02-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
