# Generated by Django 4.1.5 on 2023-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_customuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='customuser/'),
        ),
    ]
