# Generated by Django 4.1.5 on 2023-03-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='http://13.235.104.174/media/customuser/default_profile.jpg', max_length=400, null=True, upload_to='customuser/'),
        ),
    ]
