# Generated by Django 4.1.5 on 2023-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='customuser/default_profile.jpg', max_length=400, null=True, upload_to='customuser/'),
        ),
    ]
