# Generated by Django 4.1.5 on 2023-02-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_description', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('Report', 'Report'), ('Refer', 'Refer'), ('Tip Upload', 'Tip Uplod'), ('Physical', 'Physical'), ('Relationship', 'Relationship'), ('Book Reading', 'Book Reading'), ('Meditation', 'Meditation')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
