# Generated by Django 4.1.5 on 2023-02-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.TextField()),
                ('physical_badge_info', models.TextField(max_length=500)),
                ('mental_badge_info', models.TextField(max_length=500)),
                ('emotional_badge_info', models.TextField(max_length=500)),
                ('spiritual_badge_info', models.TextField(max_length=500)),
                ('beginner_info', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeName', models.CharField(max_length=200)),
                ('badgeLevel', models.IntegerField()),
                ('badgeIcon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('reading_time', models.IntegerField()),
                ('book_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('distance', models.FloatField()),
                ('calorie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DigitalWellbeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('total_usage', models.IntegerField()),
                ('unlocks', models.IntegerField()),
                ('top_1', models.CharField(max_length=100)),
                ('top_2', models.CharField(max_length=100)),
                ('top_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weight', models.FloatField()),
                ('deficit', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi_val', models.FloatField()),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mins', models.IntegerField()),
                ('record_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_set_date', models.DateField()),
                ('daily_step_target', models.IntegerField()),
                ('daily_socialmedia_target', models.IntegerField()),
                ('daily_bookpages_target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_for', models.CharField(max_length=500, unique=True)),
                ('refer_code', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_points', models.IntegerField(default=0)),
                ('neg_points', models.IntegerField(default=0)),
                ('record_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_report_category', to='club.reportcategory')),
            ],
        ),
    ]
