# Generated by Django 4.1.5 on 2023-02-12 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storyreport',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_story', to='feed.story'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refer',
            name='onboarded_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_post', to='feed.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='report_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_category', to='club.reportcategory'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalachievement',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_achievement_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meditation',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='health',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalwellbeing',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_wellbeing_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailystepcount',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_step_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_comment', to='feed.comment'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='report_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_report_category', to='club.reportcategory'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='club_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookreading',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reading_userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
