# Generated by Django 4.1.5 on 2023-02-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystepcount',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
