# Generated by Django 4.1.5 on 2023-02-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_dailystepcount_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='deficit',
            new_name='bellysize',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='height',
            new_name='height_ft',
        ),
        migrations.RemoveField(
            model_name='health',
            name='diastolic_bp',
        ),
        migrations.RemoveField(
            model_name='health',
            name='systolic_bp',
        ),
        migrations.AddField(
            model_name='health',
            name='height_in',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='hipsize',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='waist',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
