# Generated by Django 4.1.5 on 2023-02-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_relationship_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='record_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
