# Generated by Django 4.1.5 on 2023-02-24 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_relationship_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
