# Generated by Django 4.1.5 on 2023-02-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_club_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='date_joined',
        ),
    ]
