# Generated by Django 4.1.5 on 2023-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_remove_club_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
