# Generated by Django 4.1.5 on 2023-03-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_club_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='date_joined',
            new_name='date_join',
        ),
    ]
