# Generated by Django 4.1.5 on 2023-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_rename_date_joined_club_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='time_mins',
            field=models.FloatField(),
        ),
    ]
