# Generated by Django 4.1.5 on 2023-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_alter_meditation_time_mins'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='record_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
