from django.urls import path
from .views import (
     BookReadingView, 
     BookReadingWeekly,
     CommentReportViewSet, 
     MeditationView, 
     MeditationWeekly, 
     PostReportViewSet,
     RelationshipRetrieveView, 
     RelationshipView, 
     RelationshipUpdateView, 
     HealthView, 
     DailyStepCountView, 
     DailyStepCountDetailView, 
     PersonalAchievementView, 
     PersonalAchievementDetailView, 
     MeditationDetailView, 
     HealthDetailView, 
     BookReadingDetailView, 
     ReferView, 
     ReferDetailView, 
     BadgeView, 
     HelpSupportView, 
     AppDataView, 
     LeaderboardView, 
     OverallAccomplishmentView, 
     RelationshipWeekly, 
     ReportCategoryViewSet,
     ReferOnboardedView,
     Tools_state,
     FeedbackView,
     PostReportDestroyAPIView,
     HealthData,
     StoryReportViewSet)
from club.models import PostReport

from .views import (
    StepCountWeekly
)
urlpatterns = [
    path('api/book-reading/', BookReadingView.as_view(), name='api-book-reading'),
    path('api/book-reading/<int:userid>/',
         BookReadingDetailView.as_view(), name='api-book-reading-detail'),
    path('api/relationship/', RelationshipView.as_view(), name='api-relationship'),
    path('api/relationship/<int:userid>/', RelationshipRetrieveView.as_view(), name='api-relationshipRetrive'),
    # ----
       # -------
    path('api/relationship/weekly', RelationshipWeekly.as_view(),
         name='api-relationship-weekly'),
    path('api/daily-step-count/weekly', StepCountWeekly.as_view(),
         name='api-daily-step-count-weekly'),
    path('api/book-reading/weekly', BookReadingWeekly.as_view(),
         name='book-reading-weekly'),
    path('api/meditation/weekly', MeditationWeekly.as_view(),
         name='meditation-weekly'),
    # path('api/health-weekly', HealthWeekly.as_view(),
    #      name='health-weekly'),
    
    # ------
    path('api/relationship/update', RelationshipUpdateView.as_view(),
         name='api-relationship-update'),
    path('api/meditation/', MeditationView.as_view(), name='api-meditation'),
    path('api/meditation/<int:userid>',
         MeditationDetailView.as_view(), name='api-meditation-detail'),
    path('api/health/', HealthView.as_view(), name='api-health'),
    path('api/health/<int:userid>',
         HealthDetailView.as_view(), name='api-health-detail'),
    path('api/daily-step-count/', DailyStepCountView.as_view(),
         name='api-daily-step-count'),
 
    
    path('api/daily-step-count/<int:userid>',
         DailyStepCountDetailView.as_view(), name='api-daily-step-count-detail'),
    path('api/personal-achievement/', PersonalAchievementView.as_view(),
         name='api-personal-achievement'),
    path('api/personal-achievement/<int:userid>',
         PersonalAchievementDetailView.as_view(), name='api-personal-achievement-detail'),
    path('api/refer/', ReferView.as_view(), name='api-refer'),
    path('api/refer/onboarded_user', ReferOnboardedView.as_view(), name='api-refer'),
    path('api/refer/<slug:refer_code>',
         ReferDetailView.as_view(), name='api-refer-detail'),
    path('api/badge/', BadgeView.as_view(), name='api-badge'),
    path('api/help-support/', HelpSupportView.as_view(), name='api-help-support'),
    path('api/app-data/', AppDataView.as_view(), name='api-app-data'),
    path('api/leaderboard/', LeaderboardView.as_view(), name='api-leaderboard'),
    path('api/overall-accomplishment/', OverallAccomplishmentView.as_view(),
         name='api-overall-accomplishment'),
    path('api/tools_state/', Tools_state.as_view(),
         name='tools_state'),
    path('api/post/report/', PostReportViewSet.as_view(),
         name='post_report'),
    path('api/story/report/', StoryReportViewSet.as_view(),
         name='story_report'),
    path('api/comment/report/', CommentReportViewSet.as_view(),
         name='story_report'),
    path('api/report_delete/<int:pk>', PostReportDestroyAPIView.as_view(),
         name='report_delete'),
    path('api/report/category', ReportCategoryViewSet.as_view(),
         name='report_category'),
     path('api/feedback-view/', FeedbackView.as_view(),
         name='feedback-view'),

     path('api/weekly-health-data/', HealthData.as_view(),
         name='weekly-health-data'),
    
]
